apiVersion: v1
kind: ReplicationController
metadata:
  name: splunk-v6.5.2
  labels:
    name: splunk
spec:
  replicas: 1
  selector:
    name: splunk
    version: v6.5.2
  template:
    metadata:
      labels:
        name: splunk
        version: v6.5.2
    spec:
      containers:
      - name: splunk
        image: splunk/splunk:6.5.2
        ports:
        - containerPort: 8000
        - containerPort: 9997
        resources:
          requests:
            memory: "256Mi"
            cpu: "125m"
          limits:
            memory: "1024Mi"
            cpu: "250m"
        env:
        - name: SPLUNK_START_ARGS
          value: "--accept-license"
        - name: SPLUNK_USER
          value: "root"
