# Default values for fluentd-splunk.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  repository: your-repository
  tag: 1.0
  pullPolicy: IfNotPresent
volumeMounts:
  varlog: /var/log
  varlibdockercontainers: /var/lib/docker/containers
  tdAgentConfMountPath: /etc/td-agent
volumes:
  varlog: /var/log
  varlibdockercontainers: /var/lib/docker/containers
  tdAgentConfigVolumeName: td-agent-config-volume
  tdAgentConfigVolumeConfigMap: td-agent-config
pull:
  secretName : your-secret-name
deamonset:
  name: nginx
  type: ClusterIP
  externalPort: 80
  internalPort: 80
resources:
  limits:
    cpu: 100m
    memory: 128Mi